from pathlib import Path
p=Path('/mnt/data/v79work/v78work')
# migration
(p/'db/migrations/V79.sql').write_text('''CREATE TABLE IF NOT EXISTS tournament_share_verification_export_checks (\n  id TEXT PRIMARY KEY, tournament_id TEXT, export_version TEXT NOT NULL, integrity_valid INTEGER NOT NULL DEFAULT 0, signature_valid INTEGER NOT NULL DEFAULT 0, reason TEXT, created_at TEXT NOT NULL\n);\nCREATE TABLE IF NOT EXISTS tournament_share_policy_drift_ack (\n  id TEXT PRIMARY KEY, tournament_id TEXT, alert_id TEXT NOT NULL, action TEXT NOT NULL, created_at TEXT NOT NULL\n);\nCREATE TABLE IF NOT EXISTS tournament_share_replay_history_checks (\n  id TEXT PRIMARY KEY, tournament_id TEXT, replay_id TEXT NOT NULL, history_id TEXT, integrity_valid INTEGER NOT NULL DEFAULT 0, reason TEXT, created_at TEXT NOT NULL\n);\nCREATE TABLE IF NOT EXISTS tournament_share_v78_cleanup_replays (\n  id TEXT PRIMARY KEY, tournament_id TEXT, candidate_exports INTEGER NOT NULL DEFAULT 0, candidate_alerts INTEGER NOT NULL DEFAULT 0, candidate_replays INTEGER NOT NULL DEFAULT 0, integrity_sha256 TEXT, created_at TEXT NOT NULL\n);\nCREATE INDEX IF NOT EXISTS idx_tournament_share_verification_export_checks_tournament ON tournament_share_verification_export_checks(tournament_id,created_at DESC);\nCREATE INDEX IF NOT EXISTS idx_tournament_share_policy_drift_ack_tournament ON tournament_share_policy_drift_ack(tournament_id,created_at DESC);\nCREATE INDEX IF NOT EXISTS idx_tournament_share_replay_history_checks_tournament ON tournament_share_replay_history_checks(tournament_id,created_at DESC);\nCREATE INDEX IF NOT EXISTS idx_tournament_share_v78_cleanup_replays_tournament ON tournament_share_v78_cleanup_replays(tournament_id,created_at DESC);\n''')
# package
import json
pkg=json.loads((p/'package.json').read_text()); pkg['version']='79.0.0'; pkg['scripts']['regression:v79']='node scripts/regression-v79.mjs'; (p/'package.json').write_text(json.dumps(pkg,ensure_ascii=False,indent=2)+'\n')
# worker insert endpoints before readiness marker
w=p/'worker/index.ts'; s=w.read_text()
marker="    const tournamentShareVerificationExportsV78=url.pathname.match"
insert=r'''    const tournamentShareV79ExportVerify=url.pathname.match(/^\/api\/tournaments\/([^/]+)\/share\/health\/verification\/exports-v79\/verify$/); if(tournamentShareV79ExportVerify && request.method==='POST'){if(!env.DB)return json({error:'D1 yapılandırılmamış.'},{status:503});const user=await authUser(request,env);if(!user)return json({error:'Giriş gerekli.'},{status:401});try{const id=decodeURIComponent(tournamentShareV79ExportVerify[1]);const t=await env.DB.prepare(`SELECT id,created_by FROM tournaments WHERE id=?`).bind(id).first<any>();if(!t)return json({error:'Turnuva bulunamadı.'},{status:404});if(t.created_by!==user.id)return json({error:'Sadece turnuva sahibi erişebilir.'},{status:403});const body=await request.json<any>().catch(()=>({}));const unsigned:any={...body};delete unsigned.integrity;const calculated=await sha256Hex(JSON.stringify(unsigned));const supplied=String(body.integrity?.sha256||'');const integrityValid=Boolean(supplied)&&supplied===calculated;const configured=Boolean(env.SHARE_EXPORT_SIGNING_SECRET);let signatureValid=false;if(configured&&body.integrity?.signature){const expected=await hmacSha256Hex(env.SHARE_EXPORT_SIGNING_SECRET!,calculated);signatureValid=expected===String(body.integrity.signature)}const reason=!integrityValid?'integrity-mismatch':configured?(signatureValid?'verified':'signature-mismatch'):'integrity-only';await env.DB.prepare(`INSERT INTO tournament_share_verification_export_checks(id,tournament_id,export_version,integrity_valid,signature_valid,reason,created_at) VALUES(?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),id,String(body.exportVersion||'v78'),integrityValid?1:0,signatureValid?1:0,reason,new Date().toISOString()).run();return json({version:'v79',integrityValid,signatureValid,signatureConfigured:configured,reason,sha256:calculated});}catch{return json({error:'Signed verification export doğrulanamadı.'},{status:400});}}
    const tournamentShareV79ExportChecks=url.pathname.match(/^\/api\/tournaments\/([^/]+)\/share\/health\/verification\/exports-v79\/checks$/); if(tournamentShareV79ExportChecks && request.method==='GET'){if(!env.DB)return json({error:'D1 yapılandırılmamış.'},{status:503});const user=await authUser(request,env);if(!user)return json({error:'Giriş gerekli.'},{status:401});try{const id=decodeURIComponent(tournamentShareV79ExportChecks[1]);const t=await env.DB.prepare(`SELECT id,created_by FROM tournaments WHERE id=?`).bind(id).first<any>();if(!t)return json({error:'Turnuva bulunamadı.'},{status:404});if(t.created_by!==user.id)return json({error:'Sadece turnuva sahibi erişebilir.'},{status:403});const rows=(await env.DB.prepare(`SELECT id,export_version exportVersion,integrity_valid integrityValid,signature_valid signatureValid,reason,created_at createdAt FROM tournament_share_verification_export_checks WHERE tournament_id=? ORDER BY created_at DESC LIMIT 50`).bind(id).all<any>()).results||[];return json({version:'v79',rows});}catch{return json({error:'Export verification geçmişi alınamadı.'},{status:400});}}
    const tournamentShareV79DriftAction=url.pathname.match(/^\/api\/tournaments\/([^/]+)\/share\/health\/retention\/policy-drift-alerts-v79\/([^/]+)\/action$/); if(tournamentShareV79DriftAction && request.method==='POST'){if(!env.DB)return json({error:'D1 yapılandırılmamış.'},{status:503});const user=await authUser(request,env);if(!user)return json({error:'Giriş gerekli.'},{status:401});try{const id=decodeURIComponent(tournamentShareV79DriftAction[1]);const alertId=decodeURIComponent(tournamentShareV79DriftAction[2]);const t=await env.DB.prepare(`SELECT id,created_by FROM tournaments WHERE id=?`).bind(id).first<any>();if(!t)return json({error:'Turnuva bulunamadı.'},{status:404});if(t.created_by!==user.id)return json({error:'Sadece turnuva sahibi erişebilir.'},{status:403});const action=String((await request.json<any>().catch(()=>({}))).action||'');if(!['acknowledge','resolve','reopen'].includes(action))return json({error:'Geçersiz işlem.'},{status:400});await env.DB.prepare(`INSERT INTO tournament_share_policy_drift_ack(id,tournament_id,alert_id,action,created_at) VALUES(?,?,?,?,?)`).bind(crypto.randomUUID(),id,alertId,action,new Date().toISOString()).run();if(action==='resolve')await env.DB.prepare(`UPDATE tournament_share_policy_drift_alerts SET status='resolved',resolved_at=? WHERE id=? AND tournament_id=?`).bind(new Date().toISOString(),alertId,id).run();if(action==='reopen')await env.DB.prepare(`UPDATE tournament_share_policy_drift_alerts SET status='open',resolved_at=NULL WHERE id=? AND tournament_id=?`).bind(alertId,id).run();return json({version:'v79',id:alertId,action});}catch{return json({error:'Policy drift işlemi başarısız.'},{status:400});}}
    const tournamentShareV79ReplayCompare=url.pathname.match(/^\/api\/tournaments\/([^/]+)\/share\/health\/verification\/replay-v79\/compare$/); if(tournamentShareV79ReplayCompare && request.method==='POST'){if(!env.DB)return json({error:'D1 yapılandırılmamış.'},{status:503});const user=await authUser(request,env);if(!user)return json({error:'Giriş gerekli.'},{status:401});try{const id=decodeURIComponent(tournamentShareV79ReplayCompare[1]);const t=await env.DB.prepare(`SELECT id,created_by FROM tournaments WHERE id=?`).bind(id).first<any>();if(!t)return json({error:'Turnuva bulunamadı.'},{status:404});if(t.created_by!==user.id)return json({error:'Sadece turnuva sahibi erişebilir.'},{status:403});const body=await request.json<any>().catch(()=>({}));const replayId=String(body.replayId||'');const historyId=String(body.historyId||'');const replay=await env.DB.prepare(`SELECT id,integrity_sha256 FROM tournament_share_verification_replays WHERE id=? AND tournament_id=?`).bind(replayId,id).first<any>();const history=await env.DB.prepare(`SELECT id,bundle_sha256 FROM tournament_share_replay_bundle_verifications WHERE id=? AND tournament_id=?`).bind(historyId,id).first<any>();const valid=Boolean(replay&&history&&replay.integrity_sha256===history.bundle_sha256);const reason=!replay||!history?'missing-record':valid?'matched':'integrity-mismatch';await env.DB.prepare(`INSERT INTO tournament_share_replay_history_checks(id,tournament_id,replay_id,history_id,integrity_valid,reason,created_at) VALUES(?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),id,replayId,historyId,valid?1:0,reason,new Date().toISOString()).run();return json({version:'v79',replayId,historyId,integrityValid:valid,reason});}catch{return json({error:'Replay/history integrity karşılaştırması başarısız.'},{status:400});}}
    const tournamentShareV79Cleanup=url.pathname.match(/^\/api\/tournaments\/([^/]+)\/share\/health\/verification\/cleanup-replay-v79$/); if(tournamentShareV79Cleanup && request.method==='POST'){if(!env.DB)return json({error:'D1 yapılandırılmamış.'},{status:503});const user=await authUser(request,env);if(!user)return json({error:'Giriş gerekli.'},{status:401});try{const id=decodeURIComponent(tournamentShareV79Cleanup[1]);const t=await env.DB.prepare(`SELECT id,created_by FROM tournaments WHERE id=?`).bind(id).first<any>();if(!t)return json({error:'Turnuva bulunamadı.'},{status:404});if(t.created_by!==user.id)return json({error:'Sadece turnuva sahibi erişebilir.'},{status:403});const exportsOld=await env.DB.prepare(`SELECT COUNT(*) count FROM tournament_share_verification_export_checks WHERE tournament_id=? AND created_at < datetime('now','-365 day')`).bind(id).first<any>();const alertsOld=await env.DB.prepare(`SELECT COUNT(*) count FROM tournament_share_policy_drift_ack WHERE tournament_id=? AND created_at < datetime('now','-365 day')`).bind(id).first<any>();const replaysOld=await env.DB.prepare(`SELECT COUNT(*) count FROM tournament_share_replay_history_checks WHERE tournament_id=? AND created_at < datetime('now','-365 day')`).bind(id).first<any>();const payload={tournamentId:id,candidateExports:Number(exportsOld?.count||0),candidateAlerts:Number(alertsOld?.count||0),candidateReplays:Number(replaysOld?.count||0)};const integrity=await sha256Hex(JSON.stringify(payload));const rid=crypto.randomUUID();await env.DB.prepare(`INSERT INTO tournament_share_v78_cleanup_replays(id,tournament_id,candidate_exports,candidate_alerts,candidate_replays,integrity_sha256,created_at) VALUES(?,?,?,?,?,?,?)`).bind(rid,id,payload.candidateExports,payload.candidateAlerts,payload.candidateReplays,integrity,new Date().toISOString()).run();return json({version:'v79',replayId:rid,status:'dry-run',...payload,integrity:{algorithm:'SHA-256',sha256:integrity}});}catch{return json({error:'V79 cleanup replay başarısız.'},{status:400});}}
    const tournamentShareV79CleanupHistory=url.pathname.match(/^\/api\/tournaments\/([^/]+)\/share\/health\/verification\/cleanup-replay-v79\/history$/); if(tournamentShareV79CleanupHistory && request.method==='GET'){if(!env.DB)return json({error:'D1 yapılandırılmamış.'},{status:503});const user=await authUser(request,env);if(!user)return json({error:'Giriş gerekli.'},{status:401});try{const id=decodeURIComponent(tournamentShareV79CleanupHistory[1]);const t=await env.DB.prepare(`SELECT id,created_by FROM tournaments WHERE id=?`).bind(id).first<any>();if(!t)return json({error:'Turnuva bulunamadı.'},{status:404});if(t.created_by!==user.id)return json({error:'Sadece turnuva sahibi erişebilir.'},{status:403});const rows=(await env.DB.prepare(`SELECT id,candidate_exports candidateExports,candidate_alerts candidateAlerts,candidate_replays candidateReplays,integrity_sha256 integritySha256,created_at createdAt FROM tournament_share_v78_cleanup_replays WHERE tournament_id=? ORDER BY created_at DESC LIMIT 30`).bind(id).all<any>()).results||[];return json({version:'v79',rows});}catch{return json({error:'Cleanup replay geçmişi alınamadı.'},{status:400});}}
'''
if marker not in s: raise SystemExit('marker missing')
s=s.replace(marker,insert+marker,1)
s=s.replace("version:'78.0.0'","version:'79.0.0'",1)
s=s.replace("v78:'signed-verification-history-export-policy-drift-alerts-scheduled-verification-replay'","v78:'signed-verification-history-export-policy-drift-alerts-scheduled-verification-replay',v79:'signed-export-verification-alert-lifecycle-replay-history-integrity-retention-cleanup-replay'",1)
s=s.replace("'tournament_share_verification_replays'","'tournament_share_verification_replays','tournament_share_verification_export_checks','tournament_share_policy_drift_ack','tournament_share_replay_history_checks','tournament_share_v78_cleanup_replays'",1)
w.write_text(s)
# regression
(p/'scripts/regression-v79.mjs').write_text(r'''import fs from 'node:fs';
const pkg=JSON.parse(fs.readFileSync('package.json','utf8')); const worker=fs.readFileSync('worker/index.ts','utf8'); const mig=fs.readFileSync('db/migrations/V79.sql','utf8');
const checks=[pkg.version==='79.0.0',pkg.scripts['regression:v79'],mig.includes('tournament_share_verification_export_checks'),mig.includes('tournament_share_policy_drift_ack'),mig.includes('tournament_share_replay_history_checks'),mig.includes('tournament_share_v78_cleanup_replays'),worker.includes('verification/exports-v79/verify'),worker.includes('policy-drift-alerts-v79'),worker.includes('verification/replay-v79/compare'),worker.includes('verification/cleanup-replay-v79'),worker.includes("v79:'signed-export-verification-alert-lifecycle-replay-history-integrity-retention-cleanup-replay'")];
if(checks.every(Boolean)){console.log('V79 regression OK');}else{console.error('V79 regression FAILED',checks);process.exit(1)}
''')
# docs
(p/'docs/releases/V79_RELEASE_NOTES.md').write_text('''# ZATO Chess V79 Release Notes\n\n- Signed verification export server-side verification endpoint.\n- Verification export check history.\n- Policy drift alert acknowledge/resolve/reopen lifecycle.\n- Replay vs verification-history integrity comparison.\n- Deterministic V78 retention cleanup dry-run and history.\n- Owner-only operational endpoints.\n- No visitor IP/User-Agent/fingerprint data added.\n''')
(p/'docs/releases/V79_PRODUCTION_CHECKLIST.md').write_text('''# V79 Production Checklist\n\n- [x] Regression script\n- [x] Migration idempotency/data preservation\n- [x] ZIP integrity\n- [ ] Real Cloudflare D1 deployment verification\n- [ ] Browser UI smoke test against production\n- [ ] Configure SHARE_EXPORT_SIGNING_SECRET and SHARE_EXPORT_SIGNING_KEY_ID\n- [ ] Verify active/retired key lifecycle in production\n''')
ctx=p/'docs/continuation/ZATO_PROJECT_CONTEXT.md'; cs=ctx.read_text(); cs=cs.replace('# ZATO Chess — Continuation Context V78','# ZATO Chess — Continuation Context V79'); cs=cs.replace('V78 source tree and ZIP are the current continuation baseline.','V79 source tree and ZIP are the current continuation baseline.'); cs=cs.replace('## V78\n','## V79\n- Signed verification export server-side verification and verification history.\n- Policy drift alert acknowledgement/resolution/reopen lifecycle.\n- Replay-vs-history integrity comparison.\n- Deterministic V78 cleanup dry-run and cleanup replay history.\n\n## V78\n'); cs=cs.replace('V79: signed verification export verification endpoint, alert acknowledgement lifecycle, replay-vs-history integrity comparison and retention-aware V78 cleanup simulation.','V80: verification-chain export, policy alert audit-chain integrity, cleanup replay comparison, and public-share contract matrix retention policy hardening.'); ctx.write_text(cs)
