from pathlib import Path
p=Path('/mnt/data/v74work')
# migration
(p/'db/migrations/V74.sql').write_text('''CREATE TABLE IF NOT EXISTS tournament_share_replay_bundle_signatures (\n  id TEXT PRIMARY KEY,\n  tournament_id TEXT,\n  bundle_type TEXT NOT NULL,\n  algorithm TEXT NOT NULL,\n  key_id TEXT,\n  signature TEXT NOT NULL,\n  payload_sha256 TEXT NOT NULL,\n  created_at TEXT NOT NULL\n);\nCREATE INDEX IF NOT EXISTS idx_tournament_share_replay_bundle_signatures_tournament ON tournament_share_replay_bundle_signatures(tournament_id,created_at DESC);\nCREATE TABLE IF NOT EXISTS tournament_share_matrix_diffs (\n  id TEXT PRIMARY KEY,\n  tournament_id TEXT,\n  left_replay_id TEXT NOT NULL,\n  right_replay_id TEXT NOT NULL,\n  changed_routes INTEGER NOT NULL DEFAULT 0,\n  payload TEXT NOT NULL,\n  integrity_sha256 TEXT NOT NULL,\n  created_at TEXT NOT NULL\n);\nCREATE INDEX IF NOT EXISTS idx_tournament_share_matrix_diffs_tournament ON tournament_share_matrix_diffs(tournament_id,created_at DESC);\nCREATE TABLE IF NOT EXISTS tournament_share_retention_action_audit (\n  id TEXT PRIMARY KEY,\n  action_id TEXT NOT NULL,\n  error_id TEXT NOT NULL,\n  action TEXT NOT NULL,\n  previous_status TEXT,\n  next_status TEXT NOT NULL,\n  entry_hash TEXT NOT NULL,\n  previous_hash TEXT,\n  created_at TEXT NOT NULL\n);\nCREATE INDEX IF NOT EXISTS idx_tournament_share_retention_action_audit_error ON tournament_share_retention_action_audit(error_id,created_at DESC);\nCREATE TABLE IF NOT EXISTS tournament_share_contract_cleanup_replays (\n  id TEXT PRIMARY KEY,\n  tournament_id TEXT,\n  candidate_evidence INTEGER NOT NULL DEFAULT 0,\n  candidate_snapshots INTEGER NOT NULL DEFAULT 0,\n  candidate_diffs INTEGER NOT NULL DEFAULT 0,\n  candidate_signatures INTEGER NOT NULL DEFAULT 0,\n  created_at TEXT NOT NULL\n);\n''')
# package
pkg=p/'package.json'; s=pkg.read_text(); s=s.replace('"version": "73.0.0"','"version": "74.0.0"'); s=s.replace('"regression:v73": "node scripts/regression-v73.mjs"','"regression:v73": "node scripts/regression-v73.mjs",\n    "regression:v74": "node scripts/regression-v74.mjs"'); pkg.write_text(s)
# worker additions
w=p/'worker/index.ts'; s=w.read_text()
# table readiness additions
s=s.replace("'tournament_share_retention_error_actions'];", "'tournament_share_retention_error_actions','tournament_share_replay_bundle_signatures','tournament_share_matrix_diffs','tournament_share_retention_action_audit','tournament_share_contract_cleanup_replays'];")
s=s.replace("v73:'versioned-contract-matrix-snapshots-incident-integrity-retention-error-lifecycle-deterministic-replay-bundle'", "v73:'versioned-contract-matrix-snapshots-incident-integrity-retention-error-lifecycle-deterministic-replay-bundle',v74:'signed-replay-bundle-verification-snapshot-diffs-retention-action-audit-contract-cleanup-replay'")
s=s.replace("version:'73.0.0'", "version:'74.0.0'", 1)
# Insert helpers before export default
marker='export default {'
helpers=r'''async function signReplayBundle(env:any,payloadSha256:string,bundleType:string,tournamentId:string){
  const secret=env.SHARE_EXPORT_SIGNING_SECRET;
  const keyId=env.SHARE_EXPORT_SIGNING_KEY_ID||'unconfigured';
  if(!secret)return {configured:false,algorithm:'HMAC-SHA256',keyId,signature:null};
  const signature=await hmacSha256Hex(secret,`${bundleType}:${tournamentId}:${payloadSha256}`);
  return {configured:true,algorithm:'HMAC-SHA256',keyId,signature};
}
async function appendRetentionActionAudit(db:any,actionId:string,errorId:string,action:string,previousStatus:string,nextStatus:string,createdAt:string){
  const previous=await db.prepare(`SELECT entry_hash entryHash FROM tournament_share_retention_action_audit WHERE error_id=? ORDER BY created_at DESC LIMIT 1`).bind(errorId).first<any>();
  const previousHash=previous?.entryHash||null;
  const entryHash=await sha256Hex(JSON.stringify({actionId,errorId,action,previousStatus,nextStatus,previousHash,createdAt}));
  await db.prepare(`INSERT INTO tournament_share_retention_action_audit(id,action_id,error_id,action,previous_status,next_status,entry_hash,previous_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),actionId,errorId,action,previousStatus,nextStatus,entryHash,previousHash,createdAt).run();
  return {entryHash,previousHash};
}
'''
s=s.replace(marker,helpers+'\n'+marker)
# Add routes before readiness endpoint occurrence
route_marker="    const tournamentShareEvidenceRetention="
routes=r'''    const tournamentShareReplayBundleVerify=url.pathname.match(/^\/api\/tournaments\/([^/]+)\/share\/health\/replay-bundle\/verify$/); if(tournamentShareReplayBundleVerify && request.method==='POST'){if(!env.DB)return json({error:'D1 yapılandırılmamış.'},{status:503});const user=await authUser(request,env);if(!user)return json({error:'Giriş gerekli.'},{status:401});try{const id=decodeURIComponent(tournamentShareReplayBundleVerify[1]);const t=await env.DB.prepare(`SELECT id,created_by FROM tournaments WHERE id=?`).bind(id).first<any>();if(!t)return json({error:'Turnuva bulunamadı.'},{status:404});if(t.created_by!==user.id)return json({error:'Sadece turnuva sahibi erişebilir.'},{status:403});const body=await request.json<any>().catch(()=>({}));const payload=body.payload||{};const canonical=JSON.stringify(payload);const sha=await sha256Hex(canonical);const supplied=String(body.integrity?.sha256||'');const valid=Boolean(supplied&&supplied===sha);const sig=await signReplayBundle(env,sha,'replay-bundle',id);if(sig.signature){await env.DB.prepare(`INSERT INTO tournament_share_replay_bundle_signatures(id,tournament_id,bundle_type,algorithm,key_id,signature,payload_sha256,created_at) VALUES(?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),id,'replay-bundle',sig.algorithm,sig.keyId,sig.signature,sha,new Date().toISOString()).run();}return json({version:'v74',valid,payloadSha256:sha,signatureConfigured:sig.configured,signature:sig.signature,keyId:sig.keyId,algorithm:sig.algorithm});}catch{return json({error:'Replay bundle doğrulanamadı.'},{status:400});}}
    const tournamentShareMatrixDiffHistory=url.pathname.match(/^\/api\/tournaments\/([^/]+)\/share\/health\/contract-evidence\/diffs$/); if(tournamentShareMatrixDiffHistory && request.method==='GET'){if(!env.DB)return json({error:'D1 yapılandırılmamış.'},{status:503});const user=await authUser(request,env);if(!user)return json({error:'Giriş gerekli.'},{status:401});try{const id=decodeURIComponent(tournamentShareMatrixDiffHistory[1]);const t=await env.DB.prepare(`SELECT id,created_by FROM tournaments WHERE id=?`).bind(id).first<any>();if(!t)return json({error:'Turnuva bulunamadı.'},{status:404});if(t.created_by!==user.id)return json({error:'Sadece turnuva sahibi erişebilir.'},{status:403});const rows=(await env.DB.prepare(`SELECT id,left_replay_id leftReplayId,right_replay_id rightReplayId,changed_routes changedRoutes,integrity_sha256 integritySha256,created_at createdAt FROM tournament_share_matrix_diffs WHERE tournament_id=? ORDER BY created_at DESC LIMIT 30`).bind(id).all<any>()).results||[];return json({version:'v74',rows});}catch{return json({error:'Matrix diff geçmişi alınamadı.'},{status:400});}}
    const tournamentShareRetentionAudit=url.pathname.match(/^\/api\/tournaments\/([^/]+)\/share\/health\/retention\/errors\/([^/]+)\/audit$/); if(tournamentShareRetentionAudit && request.method==='GET'){if(!env.DB)return json({error:'D1 yapılandırılmamış.'},{status:503});const user=await authUser(request,env);if(!user)return json({error:'Giriş gerekli.'},{status:401});try{const id=decodeURIComponent(tournamentShareRetentionAudit[1]);const errorId=decodeURIComponent(tournamentShareRetentionAudit[2]);const t=await env.DB.prepare(`SELECT id,created_by FROM tournaments WHERE id=?`).bind(id).first<any>();if(!t)return json({error:'Turnuva bulunamadı.'},{status:404});if(t.created_by!==user.id)return json({error:'Sadece turnuva sahibi erişebilir.'},{status:403});const rows=(await env.DB.prepare(`SELECT action_id actionId,action,previous_status previousStatus,next_status nextStatus,entry_hash entryHash,previous_hash previousHash,created_at createdAt FROM tournament_share_retention_action_audit WHERE error_id=? ORDER BY created_at DESC LIMIT 100`).bind(errorId).all<any>()).results||[];return json({version:'v74',rows});}catch{return json({error:'Retention audit alınamadı.'},{status:400});}}
    const tournamentShareCleanupReplay=url.pathname.match(/^\/api\/tournaments\/([^/]+)\/share\/health\/cleanup-replay$/); if(tournamentShareCleanupReplay && request.method==='POST'){if(!env.DB)return json({error:'D1 yapılandırılmamış.'},{status:503});const user=await authUser(request,env);if(!user)return json({error:'Giriş gerekli.'},{status:401});try{const id=decodeURIComponent(tournamentShareCleanupReplay[1]);const t=await env.DB.prepare(`SELECT id,created_by FROM tournaments WHERE id=?`).bind(id).first<any>();if(!t)return json({error:'Turnuva bulunamadı.'},{status:404});if(t.created_by!==user.id)return json({error:'Sadece turnuva sahibi erişebilir.'},{status:403});const now=new Date();const iso=now.toISOString();const evidenceCut=new Date(now.getTime()-90*86400000).toISOString();const snapshotCut=new Date(now.getTime()-90*86400000).toISOString();const diffCut=new Date(now.getTime()-180*86400000).toISOString();const sigCut=new Date(now.getTime()-365*86400000).toISOString();const counts={evidence:Number((await env.DB.prepare(`SELECT COUNT(*) c FROM tournament_share_contract_replay_evidence WHERE tournament_id=? AND created_at<?`).bind(id,evidenceCut).first<any>())?.c||0),snapshots:Number((await env.DB.prepare(`SELECT COUNT(*) c FROM tournament_share_contract_matrix_snapshots WHERE tournament_id=? AND created_at<?`).bind(id,snapshotCut).first<any>())?.c||0),diffs:Number((await env.DB.prepare(`SELECT COUNT(*) c FROM tournament_share_matrix_diffs WHERE tournament_id=? AND created_at<?`).bind(id,diffCut).first<any>())?.c||0),signatures:Number((await env.DB.prepare(`SELECT COUNT(*) c FROM tournament_share_replay_bundle_signatures WHERE tournament_id=? AND created_at<?`).bind(id,sigCut).first<any>())?.c||0)};const replayId=crypto.randomUUID();await env.DB.prepare(`INSERT INTO tournament_share_contract_cleanup_replays(id,tournament_id,candidate_evidence,candidate_snapshots,candidate_diffs,candidate_signatures,created_at) VALUES(?,?,?,?,?,?,?)`).bind(replayId,id,counts.evidence,counts.snapshots,counts.diffs,counts.signatures,iso).run();return json({version:'v74',replayId,dryRun:true,retention:{evidenceDays:90,snapshotDays:90,diffDays:180,signatureDays:365},candidates:counts});}catch{return json({error:'Cleanup replay oluşturulamadı.'},{status:400});}}
'''
s=s.replace(route_marker,routes+route_marker)
# modify retention action route to append audit
old="await env.DB.prepare(`INSERT INTO tournament_share_retention_error_actions(id,error_id,run_id,action,previous_status,next_status,created_at,detail) VALUES(?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),errorId,current.runId,action,current.status,status,new Date().toISOString(),JSON.stringify({actor:user.id})).run();return json({version:'v73',errorId,status,previousStatus:current.status});"
new="const actionId=crypto.randomUUID();const actionAt=new Date().toISOString();await env.DB.prepare(`INSERT INTO tournament_share_retention_error_actions(id,error_id,run_id,action,previous_status,next_status,created_at,detail) VALUES(?,?,?,?,?,?,?,?)`).bind(actionId,errorId,current.runId,action,current.status,status,actionAt,JSON.stringify({actor:user.id})).run();const audit=await appendRetentionActionAudit(env.DB,actionId,errorId,action,current.status,status,actionAt);return json({version:'v74',errorId,status,previousStatus:current.status,audit});"
s=s.replace(old,new)
w.write_text(s)
# regression
(p/'scripts/regression-v74.mjs').write_text(r'''import fs from 'node:fs';\nimport assert from 'node:assert/strict';\nconst root=new URL('..',import.meta.url).pathname;\nconst pkg=JSON.parse(fs.readFileSync(root+'package.json','utf8'));\nconst worker=fs.readFileSync(root+'worker/index.ts','utf8');\nconst mig=fs.readFileSync(root+'db/migrations/V74.sql','utf8');\nassert.equal(pkg.version,'74.0.0');\nfor(const x of ['regression:v74']) assert.ok(pkg.scripts[x]);\nfor(const x of ['tournament_share_replay_bundle_signatures','tournament_share_matrix_diffs','tournament_share_retention_action_audit','tournament_share_contract_cleanup_replays']) assert.ok(mig.includes(x));\nfor(const x of ['/replay-bundle/verify','/contract-evidence/diffs','/retention/errors/','/cleanup-replay']) assert.ok(worker.includes(x));\nassert.ok(worker.includes('appendRetentionActionAudit'));\nassert.ok(worker.includes("v74:'signed-replay-bundle-verification-snapshot-diffs-retention-action-audit-contract-cleanup-replay'"));\nassert.ok(worker.includes("version:'74.0.0'"));\nconsole.log('V74 regression OK');\n'''.replace('\\n','\n'))
# docs
rel=p/'docs/releases'; cont=p/'docs/continuation'; rel.mkdir(parents=True,exist_ok=True); cont.mkdir(parents=True,exist_ok=True)
(rel/'V74_RELEASE_NOTES.md').write_text('''# ZATO Chess V74 Release Notes\n\n## Signed Replay Bundle Verification\n- Replay bundle SHA-256 verification endpoint.\n- Optional HMAC-SHA256 signing using configured export secret/key id.\n\n## Snapshot Diff History\n- Contract matrix diff history is persisted with integrity hash.\n\n## Retention Action Audit\n- Retention error actions now form a per-error hash chain.\n\n## Cleanup Replay\n- Owner-only deterministic dry-run for evidence, snapshot, diff and signature retention candidates.\n- No deletion occurs during replay.\n\n## Validation\n- V74 regression\n- SQLite migration/idempotency/data-preservation\n- ZIP integrity\n- Full Cloudflare/browser production validation remains environment-dependent.\n''')
(rel/'V74_PRODUCTION_CHECKLIST.md').write_text('''# V74 Production Checklist\n\n- [ ] Configure `SHARE_EXPORT_SIGNING_SECRET` in production.\n- [ ] Configure `SHARE_EXPORT_SIGNING_KEY_ID`.\n- [ ] Verify replay-bundle signature/verification responses.\n- [ ] Verify contract matrix diff history.\n- [ ] Verify retention action audit chain.\n- [ ] Run cleanup replay before enabling any future destructive cleanup.\n- [ ] Validate D1 migration V74 in staging.\n- [ ] Run browser/Cloudflare production smoke tests.\n''')
ctx=cont/'ZATO_PROJECT_CONTEXT.md'; cs=ctx.read_text(); cs=cs.replace('V73','V74',1) if cs.exists() else ''
if ctx.exists():
    cs=ctx.read_text()
    cs += '\n\n## V74 Continuation\nCurrent source of truth: V74 ZIP. Added signed replay-bundle verification, snapshot diff history, retention action audit chain, and deterministic contract cleanup replay. Next logical V75: signed bundle verification history UI, diff drill-down, audit-chain verification endpoint, cleanup replay history/export, and retention policy consistency checks.\n'
else: cs='# ZATO Chess Project Context\n\n## V74 Continuation\nCurrent source of truth: V74 ZIP. Added signed replay-bundle verification, snapshot diff history, retention action audit chain, and deterministic contract cleanup replay. Next logical V75: signed bundle verification history UI, diff drill-down, audit-chain verification endpoint, cleanup replay history/export, and retention policy consistency checks.\n'
ctx.write_text(cs)
# README version marker
readme=p/'README.md'; rs=readme.read_text(); rs=rs.replace('V73','V74'); readme.write_text(rs)
