from pathlib import Path
p=Path('/mnt/data/v44work/worker/index.ts'); s=p.read_text()
s=s.replace("const m=await db.prepare(`SELECT id,tournament_id,round,match_no,player1_id,player2_id,status FROM tournament_matches WHERE game_id=?`).bind(gameId).first<any>();", "const m=await db.prepare(`SELECT id,tournament_id,round,match_no,player1_id,player2_id,status,game_id,tiebreak_game_id,tiebreak_mode,tiebreak_room_code FROM tournament_matches WHERE game_id=? OR tiebreak_game_id=? ORDER BY CASE WHEN tiebreak_game_id=? THEN 0 ELSE 1 END LIMIT 1`).bind(gameId,gameId,gameId).first<any>();")
old="""  let winnerId=result==='1-0'?m.player1_id:result==='0-1'?m.player2_id:null;\n  let winnerReason=winnerId?'game_result':'draw_seed_tiebreak';\n  if(!winnerId) {\n    const seeded=(await db.prepare(`SELECT user_id,seed FROM tournament_players WHERE tournament_id=? AND user_id IN (?,?) ORDER BY CASE WHEN seed IS NULL THEN 999999 ELSE seed END ASC LIMIT 1`).bind(m.tournament_id,m.player1_id,m.player2_id).first<any>());\n    winnerId=seeded?.user_id||m.player1_id||m.player2_id;\n    winnerReason='draw_seed_tiebreak';\n  }\n  await db.prepare(`UPDATE tournament_matches SET status='finished',winner_id=?,game_id=?,winner_reason=?,tie_break=? WHERE id=? AND status<>'finished'`).bind(winnerId,gameId,winnerReason,winnerReason==='draw_seed_tiebreak'?'seed':'none',m.id).run();\n"""
new="""  const isReplayGame=String(m.tiebreak_game_id||'')===String(gameId);\n  let winnerId=result==='1-0'?m.player1_id:result==='0-1'?m.player2_id:null;\n  let winnerReason=winnerId?'game_result':(isReplayGame?'draw_after_replay':'draw_seed_tiebreak');\n  if(!winnerId && !isReplayGame && String(m.tiebreak_mode||'seed')==='replay' && m.status!=='tiebreak') {\n    const replayCode=tournamentRoomCode();\n    await db.prepare(`UPDATE tournament_matches SET status='tiebreak',tiebreak_room_code=?,tiebreak_mode='replay',tie_break='replay',winner_reason='pending_replay' WHERE id=? AND status<>'finished'`).bind(replayCode,m.id).run();\n    const names=await db.prepare(`SELECT id,display_name FROM users WHERE id IN (?,?)`).bind(m.player1_id,m.player2_id).all<any>();\n    const byId=new Map((names.results||[]).map((x:any)=>[x.id,x.display_name]));\n    for(const uid of [m.player1_id,m.player2_id]) if(uid) await notify(db,env,uid,'tournament_update','Tie-break maçı hazır',`Ana maç berabere bitti. Tie-break için ${byId.get(uid===m.player1_id?m.player2_id:m.player1_id)||'rakibin'} ile yeni odaya bağlanabilirsin.`,{tournamentId:m.tournament_id,matchId:m.id,roomCode:replayCode,round:Number(m.round),matchNo:Number(m.match_no),tieBreak:'replay'});\n    return;\n  }\n  if(!winnerId) {\n    const seeded=(await db.prepare(`SELECT user_id,seed FROM tournament_players WHERE tournament_id=? AND user_id IN (?,?) ORDER BY CASE WHEN seed IS NULL THEN 999999 ELSE seed END ASC LIMIT 1`).bind(m.tournament_id,m.player1_id,m.player2_id).first<any>());\n    winnerId=seeded?.user_id||m.player1_id||m.player2_id;\n    winnerReason=isReplayGame?'draw_seed_after_replay':'draw_seed_tiebreak';\n  }\n  const finalTieBreak=winnerReason.includes('seed')?'seed':isReplayGame?'replay':'none';\n  await db.prepare(`UPDATE tournament_matches SET status='finished',winner_id=?,game_id=COALESCE(game_id,?),winner_reason=?,tie_break=? WHERE id=? AND status<>'finished'`).bind(winnerId,gameId,winnerReason,finalTieBreak,m.id).run();\n"""
if old not in s: raise SystemExit('tournament block not found')
s=s.replace(old,new)
s=s.replace("if (next) {", "if (next) {",1)
s=s.replace("SELECT t.id,t.name,t.time_control,t.max_players,t.status,t.created_at,t.starts_at,t.ends_at,COUNT(tp.user_id) participants", "SELECT t.id,t.name,t.time_control,t.max_players,t.status,t.tiebreak_mode,t.created_at,t.starts_at,t.ends_at,COUNT(tp.user_id) participants")
s=s.replace("const id=decodeURIComponent(tournamentMatch[1]); const t=await env.DB.prepare(`SELECT t.*,u.display_name creator_name FROM tournaments t JOIN users u ON u.id=t.created_by WHERE t.id=?`).bind(id).first<any>();", "const id=decodeURIComponent(tournamentMatch[1]); const t=await env.DB.prepare(`SELECT t.*,u.display_name creator_name FROM tournaments t JOIN users u ON u.id=t.created_by WHERE t.id=?`).bind(id).first<any>();")
s=s.replace("SELECT m.*,u1.display_name player1_name,u2.display_name player2_name,uw.display_name winner_name", "SELECT m.*,u1.display_name player1_name,u2.display_name player2_name,uw.display_name winner_name")
# create mode
s=s.replace("const maxPlayers=Number(b.maxPlayers||8); if(!TIME_CONTROLS[timeControl]||![4,8].includes(maxPlayers))", "const maxPlayers=Number(b.maxPlayers||8); const tiebreakMode=String(b.tiebreakMode||'seed'); if(!TIME_CONTROLS[timeControl]||![4,8].includes(maxPlayers)||!['seed','replay'].includes(tiebreakMode))")
s=s.replace("INSERT INTO tournaments(id,name,time_control,max_players,status,created_by) VALUES(?,?,?,?, 'registration',?)`,id,name,timeControl,maxPlayers,user.id", "INSERT INTO tournaments(id,name,time_control,max_players,tiebreak_mode,status,created_by) VALUES(?,?,?,?,?, 'registration',?)`,id,name,timeControl,maxPlayers,tiebreakMode,user.id")
# history route before tournament list
needle="    if (url.pathname === '/api/tournaments' && request.method === 'GET') {"
hist="""    if (url.pathname === '/api/tournaments/history' && request.method === 'GET') {\n      if(!env.DB)return json({error:'D1 yapılandırılmamış.'},{status:503}); const user=await authUser(request,env); if(!user)return json({error:'Giriş gerekli.'},{status:401});\n      try {\n        const limit=Math.min(24,Math.max(1,Number(url.searchParams.get('limit')||12)));\n        const rows=(await env.DB.prepare(`SELECT t.id,t.name,t.time_control,t.max_players,t.tiebreak_mode,t.created_at,t.starts_at,t.ends_at,u.display_name creator_name FROM tournaments t JOIN users u ON u.id=t.created_by WHERE t.status='finished' ORDER BY t.ends_at DESC LIMIT ?`).bind(limit).all<any>()).results||[];\n        const history=[] as any[];\n        for(const t of rows){\n          const reward=await env.DB.prepare(`SELECT rank,reward_key FROM tournament_rewards WHERE tournament_id=? AND user_id=?`).bind(t.id,user.id).first<any>();\n          const matchCount=await env.DB.prepare(`SELECT COUNT(*) count FROM tournament_matches WHERE tournament_id=?`).bind(t.id).first<any>();\n          const won=await env.DB.prepare(`SELECT COUNT(*) count FROM tournament_matches WHERE tournament_id=? AND winner_id=?`).bind(t.id,user.id).first<any>();\n          history.push({...t,matches:Number(matchCount?.count||0),wins:Number(won?.count||0),reward:reward?{rank:Number(reward.rank),rewardKey:reward.reward_key}:null});\n        }\n        return json({history});\n      } catch { return json({error:'Turnuva geçmişi yüklenemedi.'},{status:400}); }\n    }\n"""
if needle not in s: raise SystemExit('history insertion point missing')
s=s.replace(needle,hist+needle)
# room auth include tiebreak
oldauth="SELECT t.time_control,t.status,t.player1_id,t.player2_id FROM tournament_matches m JOIN tournaments t ON t.id=m.tournament_id WHERE m.room_code=?"
newauth="SELECT t.time_control,t.status,m.player1_id,m.player2_id,m.tiebreak_room_code,m.tiebreak_game_id FROM tournament_matches m JOIN tournaments t ON t.id=m.tournament_id WHERE m.room_code=? OR m.tiebreak_room_code=?"
s=s.replace(oldauth,newauth).replace("`).bind(code).first<any>(); if(tm){ const spectator", "`).bind(code,code).first<any>(); if(tm){ const spectator")
s=s.replace("if(!spectator && tm.status!=='active')return json({type:'room:error',message:'Bu turnuva odası yalnızca eşleşmedeki oyunculara açıktır.'},{status:403});", "if(!spectator && tm.status!=='active' && tm.status!=='tiebreak')return json({type:'room:error',message:'Bu turnuva odası yalnızca aktif eşleşmeye açıktır.'},{status:403}); if(!spectator && user.id!==tm.player1_id && user.id!==tm.player2_id)return json({type:'room:error',message:'Bu turnuva maçında oyuncu değilsiniz.'},{status:403});")
# persist tournament association
old="await this.env.DB.prepare(`UPDATE tournament_matches SET game_id=? WHERE room_code=? AND status IN ('ready','live')`).bind(this.gameId,this.roomCode).run(); await tournamentAfterGame"
new="await this.env.DB.prepare(`UPDATE tournament_matches SET game_id=? WHERE room_code=? AND status IN ('ready','live')`).bind(this.gameId,this.roomCode).run(); await this.env.DB.prepare(`UPDATE tournament_matches SET tiebreak_game_id=? WHERE tiebreak_room_code=? AND status='tiebreak'`).bind(this.gameId,this.roomCode).run(); await tournamentAfterGame"
if old not in s: raise SystemExit('persist association not found')
s=s.replace(old,new)
p.write_text(s)

# schema
p=Path('/mnt/data/v44work/db/schema.sql'); s=p.read_text()
s=s.replace("  ends_at TEXT,\n  FOREIGN KEY (created_by)", "  ends_at TEXT,\n  tiebreak_mode TEXT NOT NULL DEFAULT 'seed',\n  FOREIGN KEY (created_by)")
s=s.replace("  CHECK (status IN ('registration','active','finished','cancelled'))", "  CHECK (status IN ('registration','active','finished','cancelled')),\n  CHECK (tiebreak_mode IN ('seed','replay'))")
s=s.replace("  game_id TEXT,\n  winner_id TEXT,\n  tie_break TEXT", "  game_id TEXT,\n  tiebreak_game_id TEXT,\n  tiebreak_room_code TEXT UNIQUE,\n  winner_id TEXT,\n  tie_break TEXT")
s=s.replace("CHECK (status IN ('ready','live','finished','bye'))", "CHECK (status IN ('ready','live','finished','bye','tiebreak'))")
s=s.replace("CREATE INDEX IF NOT EXISTS idx_tournament_matches_game ON tournament_matches(game_id);", "CREATE INDEX IF NOT EXISTS idx_tournament_matches_game ON tournament_matches(game_id);\nCREATE INDEX IF NOT EXISTS idx_tournament_matches_tiebreak_game ON tournament_matches(tiebreak_game_id);\nCREATE INDEX IF NOT EXISTS idx_tournament_matches_tiebreak_room ON tournament_matches(tiebreak_room_code);")
p.write_text(s)
