import fs from 'node:fs';
import assert from 'node:assert/strict';
const worker=fs.readFileSync('worker/index.ts','utf8');
const app=fs.readFileSync('src/App.tsx','utf8');
const css=fs.readFileSync('src/styles.css','utf8');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
assert.equal(pkg.version,'55.0.0');
assert.match(worker,/tournamentShareHealth/);
assert.match(worker,/x-zato-cache/);
assert.match(worker,/conditional-hit/);
assert.match(worker,/origin-miss/);
assert.match(worker,/conditional304/);
assert.match(worker,/v55:'share-health-ux-cache-diagnostics-link-regeneration-route-simulation'/);
assert.equal((worker.match(/const etag=/g)||[]).length,1,'cachedJson must have one ETag declaration');
for (const marker of ['publicShareMatch','publicReplayMatch','publicOgMatch','publicSharePage','tournamentShareStats','tournamentShareHealth','tournamentShareMatch','tournamentShareUpdate','tournamentShareRevoke']) assert.match(worker,new RegExp('const '+marker));
assert.match(app,/tournamentShareHealth/);
assert.match(app,/Yeni public link/);
assert.match(app,/share-health-status/);
assert.match(app,/304 yanıtları görüntülenme sayacını artırmaz/);
assert.match(css,/share-diagnostics/);
assert.match(css,/share-health-status/);
console.log('V55 route/UI regression OK');
