import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('..',import.meta.url).pathname;
const worker=fs.readFileSync(root+'worker/index.ts','utf8');
const migration=fs.readFileSync(root+'db/migrations/V51.sql','utf8');
const ctx=fs.readFileSync(root+'ZATO_PROJECT_CONTEXT.md','utf8');
assert.match(migration,/expires_at TEXT/);
assert.match(migration,/visibility TEXT NOT NULL DEFAULT 'public'/);
assert.match(migration,/idx_tournament_shares_active/);
assert.match(worker,/version:'51\.0\.0'/);
assert.match(worker,/visibility='public'/);
assert.match(worker,/expires_at IS NULL OR expires_at>\?/);
assert.match(worker,/method==='PATCH'/);
assert.match(worker,/method==='DELETE'/);
assert.match(worker,/Sadece turnuva sahibi paylaşım oluşturabilir/);
assert.match(worker,/Sadece turnuva sahibi paylaşımı yönetebilir/);
assert.match(worker,/Otomatik/);
assert.doesNotMatch(worker,/INSERT INTO tournament_shares\(id,tournament_id,token_hash,created_by\)/);
assert.match(ctx,/V51/);
console.log('V51 regression OK');
