import fs from 'node:fs';
import assert from 'node:assert/strict';
const worker=fs.readFileSync('worker/index.ts','utf8');
const app=fs.readFileSync('src/App.tsx','utf8');
const css=fs.readFileSync('src/styles.css','utf8');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const migration=fs.readFileSync('db/migrations/V56.sql','utf8');
assert.equal(pkg.version,'56.0.0');
assert.match(pkg.scripts['regression:v56'],/regression-v56/);
assert.match(migration,/CREATE TABLE IF NOT EXISTS tournament_share_audit/);
assert.match(worker,/async function cachedHtml/);
assert.match(worker,/x-zato-cache/);
assert.match(worker,/conditional-hit/);
assert.match(worker,/origin-miss/);
assert.match(worker,/tournament_share_audit/);
assert.match(worker,/logShareAudit/);
assert.match(worker,/v56:'share-html-etag-rotation-audit-and-public-route-contracts'/);
assert.match(worker,/const page=sharePage/);
assert.match(worker,/if\(response\.status===200\).*views_count=views_count\+1/s);
assert.match(worker,/SELECT event,metadata,created_at FROM tournament_share_audit/);
for (const marker of ['publicShareMatch','publicReplayMatch','publicOgMatch','publicSharePage','tournamentShareStats','tournamentShareHealth','tournamentShareMatch','tournamentShareUpdate','tournamentShareRevoke']) assert.match(worker,new RegExp('const '+marker));
assert.match(app,/HTML ETag \+ 60 sn/);
assert.match(app,/Son paylaşım işlemleri/);
assert.match(app,/Token yenilendi/);
assert.match(css,/share-audit/);
console.log('V56 public-share route contract regression OK');
