import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('..',import.meta.url).pathname;
const worker=fs.readFileSync(root+'worker/index.ts','utf8');
const app=fs.readFileSync(root+'src/App.tsx','utf8');
const migration=fs.readFileSync(root+'db/migrations/V49.sql','utf8');
const schema=fs.readFileSync(root+'db/schema.sql','utf8');
const pkg=JSON.parse(fs.readFileSync(root+'package.json','utf8'));
const ctx=fs.readFileSync(root+'ZATO_PROJECT_CONTEXT.md','utf8');
const notes=fs.readFileSync(root+'V49_RELEASE_NOTES.md','utf8');
assert.equal(pkg.version,'49.0.0');
assert.match(worker,/version:'49\.0\.0'/);
assert.match(worker,/sha256Hex/);
assert.match(worker,/publicShareMatch/);
assert.match(worker,/publicSharePage/);
assert.match(worker,/tournamentShareMatch/);
assert.match(worker,/revoked_at/);
assert.match(worker,/cache-control/);
assert.match(app,/Public link/);
assert.match(app,/\/api\/tournaments\/\$\{encodeURIComponent\(tournamentDetail\.tournament\.id\)\}\/share/);
assert.match(migration,/CREATE TABLE IF NOT EXISTS tournament_shares/);
assert.match(migration,/token_hash TEXT NOT NULL UNIQUE/);
assert.match(schema,/CREATE TABLE IF NOT EXISTS tournament_shares/);
assert.match(ctx,/V49 — CURRENT CONTINUATION/);
assert.match(ctx,/Public Tournament Share/);
assert.match(notes,/Open Graph/);
console.log('V49 regression OK');
